defaults: &defaults
  working_directory: ~/sulo
  docker:
    - image: circleci/clojure:lein-2.7.1
  environment:
    JVM_OPTS: -Xmx3200m
    LEIN_FAST_TRAMPOLINE: yes
    CLJS_BUILD_ID: release
    AWS_DEFAULT_REGION: us-east-1

version: 2
jobs:
  clojure_deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: clojure-deps-{{ checksum "project.clj" }}
      - run: |
          lein do deps, with-profile web deps, with-profile tester deps
      - save_cache:
          key: clojure-deps-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
            - ~/.lein

  npm_deps:
    working_directory: ~/sulo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: |
              'sudo yarn add global npm'
              npm --version
      - restore_cache:
          key: node6-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: node6-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - restore_cache:
          key: foundation6-deps-{{ checksum "sulo-style/package-lock.json" }}-{{ checksum "sulo-style/bower.json" }}
      - run:
          name: install-foundation-deps
          command: |
            cd sulo-style
            npm install
            ../node_modules/bower/bin/bower install
      - save_cache:
          key: foundation6-deps-{{ checksum "sulo-style/package-lock.json" }}-{{ checksum "sulo-style/bower.json" }}
          paths:
            - ./sulo-style/node_modules
            - ./sulo-style/bower_components

  test_clj:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: clojure-deps-{{ checksum "project.clj" }}
      - run: lein test

  test_cljs:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: clojure-deps-{{ checksum "project.clj" }}
      - restore_cache:
          key: node6-deps-{{ checksum "package-lock.json" }}
      - run: ./scripts/run-cljs-tests.sh

  build_css:
    working_directory: ~/sulo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: node6-deps-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: foundation6-deps-{{ checksum "sulo-style/package-lock.json" }}-{{ checksum "sulo-style/bower.json" }}
      - attach_workspace:
          at: ~/sulo
      - run: |
          cd sulo-style
          node ../node_modules/foundation-cli/bin/foundation.js build
      - persist_to_workspace:
          root: .
          paths: ./resources/public/assets/css


  build_clj:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: clojure-deps-{{ checksum "project.clj" }}
      - attach_workspace:
          at: ~/sulo
      - run: lein uberjar
      - run: mv target/uberjar/budget-*-standalone.jar target/uberjar/budget-uberjar.jar
      - persist_to_workspace:
          root: .
          paths: target/uberjar/budget-uberjar.jar

  build_cljs:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: clojure-deps-{{ checksum "project.clj" }}
      - attach_workspace:
          at: ~/sulo
      - run: lein prod-build-web
      - save_cache:
          key: clojure-deps-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - persist_to_workspace:
          root: .
          paths: resources/public/release/js/out/budget.js

  create_final_jar:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/sulo
      - run: jar uf target/uberjar/budget-uberjar.jar resources/public/release/js/out/budget.js resources/public/assets/css
      - persist_to_workspace:
          root: .
          paths: target/uberjar/budget-uberjar.jar
      - store_artifacts:
          path: target/uberjar/budget-uberjar.jar
          destination: uberjar

  docker_build:
    working_directory: ~/sulo
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      TIMBRE_LEVEL: :info
      PORT: 8080
    steps:
      - checkout
      - attach_workspace:
          at: ~/sulo
      - setup_remote_docker
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - docker-{{ .circle-sha }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .circle-sha }}
          paths:
            - /caches/app.tar
      - persist_to_workspace:
          root: .
          paths: /caches/app.tar

  docker_test:
    working_directory: ~/sulo
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      TIMBRE_LEVEL: :info
      PORT: 8080
    steps:
      - checkout
      - attach_workspace:
          at: ~/sulo
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run: |
          docker run -d -e "PORT=$PORT" -e "CLJS_BUILD_ID=$CLJS_BUILD_ID" -e "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" -e "FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT" -e "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" -p $PORT:$PORT app; sleep 15
          docker ps -l
          docker ps -l -q | xargs docker logs
          ./scripts/run-docker-img-test.sh localhost $PORT
          docker ps -l -q | xargs docker logs

  docker_push:
    working_directory: ~/sulo
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      DOCKER_IMAGE: sulolive/sulo:$CIRCLE_SHA1
    steps:
      - attach_workspace:
          at: ~/sulo
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run: |
          docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_IMAGE



workflows:
  version: 2
  doit:
    jobs:
      - npm_deps
      - build_css:
          requires:
            - npm_deps
      - clojure_deps:
          requires:
            - build_css
      - test_clj:
          requires:
            - build_css
            - clojure_deps
      - test_cljs:
          requires:
            - build_css
            - npm_deps
            - clojure_deps
      - build_clj:
          requires:
            - test_clj
            - test_cljs
            - clojure_deps
      - build_cljs:
          requires:
            - test_clj
            - test_cljs
            - clojure_deps
      - create_final_jar:
          requires:
            - build_clj
            - build_cljs
            - build_css
      - docker_build:
          requires:
            - create_final_jar
      - docker_test:
          requires:
            - docker_build
      - docker_push:
          requires:
            - docker_test
          filters:
            branches:
              only: master
