platform :ios, '9.0'

target 'JourMoneyApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JourMoneyApp

  target 'JourMoneyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
